### ISSUE TITLE
'pelican'/'fab publish' commands don't generate Pages since 3.7 update

### ISSUE THREAD

**Issue by fxer** [pR0Ps/pelican-subtle#34]
It looks like adding Pelican 3.7 support in commit c6a3442e37494a1ddbe7668828e3d796ea866c98 caused the 'pelican' command, which generates pages for prod deployment, to stop generating Pages (like my About page). Specifically changing `pages` to `PAGES` in that commit seems to be the problem, as reverting it on my local copy makes Pages generate again. 

This is only a problem when generating files for prod on my system, the development server still creates Pages like it should.

From the [Pelican 3.7 changelog](http://docs.getpelican.com/en/stable/changelog.html):
> Remove `PAGES` context variable for themes in favor of `pages`

But it looks like the commit referenced above went in the opposite direction. Is there a reason for that I'm missing? Thanks!

**Comment by pR0Ps** [comment]
Nope, the only reason is that I misread it, thanks for the report!
